version: 2
base_image: &base_image
  image: circleci/node:16.3.0

jobs:
  npm_install:
    docker:
      - <<: *base_image
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v2-{{ .Branch }}
            - yarn-packages-v2-master
            - yarn-packages-v2-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  lint:
    docker:
      - <<: *base_image
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v2-{{ .Branch }}
            - yarn-packages-v2-master
            - yarn-packages-v2-
      - run:
          name: lint
          command: yarn lint
  test:
    docker:
      - <<: *base_image
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v2-{{ .Branch }}
            - yarn-packages-v2-master
            - yarn-packages-v2-
      - run:
          name: Test
          command: yarn test
workflows:
  version: 2
  test:
    jobs:
      - npm_install
      - lint:
          requires:
            - npm_install
      - test:
          requires:
            - npm_install
